name: Deploy PRE

on: 
  workflow_run:
    workflows: ["new_release"]
    types:
      - completed
jobs:
  deploy_PRE:
    runs-on: ubuntu-latest
    environment: PRE
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.GH_TOKEN }}
            ref: 'main'
      - uses: actions/checkout@v3
        with:
          repository: pcorcobado/ansible-playbook
          token: ${{ secrets.GH_TOKEN }}
          path: ansible
          ref: 'main'
      - uses: actions/checkout@v3
        with:
          repository: pcorcobado/filetransfer-inventory
          token: ${{ secrets.GH_TOKEN }}
          path: inventory
          ref: 'main'
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }} 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Get artifact
        id: gartif
        run: |
          VERSION=`grep -m 1 "</version>" pom.xml | sed 's/.*<version>//' | sed 's/<\/version>//'`
          ARTIFACTID=`grep -m 1 "<artifactId>" pom.xml | sed 's/.*<artifactId>//' | sed 's/<\/artifactId>//'`
          GROUPID=`grep -m 1 "<groupId>" pom.xml | sed 's/.*<groupId>//' | sed 's/<\/groupId>//'`
          ARTIFACT="${ARTIFACTID}-${VERSION}.zip"
          
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "ARTIFACTID=$ARTIFACTID" >> $GITHUB_OUTPUT
          
          aws codeartifact get-package-version-asset --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --repository ${{ secrets.CODEARTIFACT_REPOSITORY }} \
          --format maven --namespace ${GROUPID} --package ${ARTIFACTID} --package-version ${VERSION} \
          --asset ${ARTIFACT} \
          target/${ARTIFACT}
      - name: get runner ip address
        id: ip
        uses: haythem/public-ip@v1.3
      - name: whitelist runner ip address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: Deploy PRE
        id: dpre
        run: |
          ansible-playbook --user ubuntu -i inventory/PRE/host ansible/deploy_filetransfer.yml -e "artifactId=${{ steps.gartif.outputs.ARTIFACTID }}" -e "version=${{ steps.gartif.outputs.VERSION }}" -e "target=PRE" -e "workspace=${PWD}"
      - name: revoke runner ip address
        if: success() || steps.dpre.conclusion == 'failure'
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SG }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
