name: filetransfer ci/cd

on: 
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: build
#      - uses: actions/checkout@v3
#        with:
#          repository: machacamoya/ansible-playbook
#          token: ${{ secrets.MYPAT }}
#          path: master
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build snapshoot
        run: |
          pwd
          ls -ltr
          mvn -ntp -B clean verify -DskipITs=true
          pwd
          ls -ltr
          type ansible
          type ansible-playbook
  Unit_Testing:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - name: Ejecutando comando
          run: |
            echo -e "ESTOY EN UNIT TESTING\n"
  Code_Analysis:
      needs: [Unit_Testing]
      runs-on: ubuntu-latest
      steps:
        - name: Ejecutando comando
          run: |
            echo -e "ESTOY EN CODE ANALYSIS\n"
  Nexus:
      needs: [Code_Analysis]
      runs-on: ubuntu-latest
      steps:
        - name: Ejecutando comando
          run: |
            echo -e "ESTOY EN NEXUS\n"
  Deploy_CERT:
      needs: [Nexus]
      runs-on: ubuntu-latest
      steps:
        - name: Ejecutando comando
          run: |
            echo -e "ESTOY EN DEPLOY CERT\n"
  Deploy_PRE:
      needs: [Deploy_CERT]
      runs-on: ubuntu-latest
      steps:
        - name: Ejecutando comando
          run: |
            echo -e "ESTOY EN DEPLOY PRE\n"
  Deploy_PRO:
      needs: [Deploy_PRE]
      runs-on: ubuntu-latest
      steps:
        - name: Ejecutando comando
          run: |
            echo -e "ESTOY EN DEPLOY PRO\n"
