name: new_release

on: 
  release:
    types: [published]
    branches: [develop]

jobs:
  is_release:
    runs-on: ubuntu-latest
    environment: PRE
    steps:
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.GH_TOKEN }}
            ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Update snapshoot
        run: |
          git fetch origin develop --depth 1
          git checkout -b develop origin/develop
          
          VERSION=`grep "\-SNAPSHOT</version>" pom.xml | sed 's/.*<version>//' | sed 's/-SNAPSHOT<\/version>//' | awk -F "." '{printf "%s.%s.%s", $1, $2, 0}'`
          NEW_VERSION=`echo ${VERSION} | awk -F "." '{printf "%s.%s.%s", $1+1, $2, $3}'`
          timestamp=`date +"%s"`

          git config --global user.email "corcobadopedro@gmail.com"
          git config --global user.name "corcobadopedro"
          git ls-remote --tags origin v${VERSION}
          git ls-remote --heads origin release-*
          
          
          git checkout -b release-${VERSION}-${timestamp} develop
          mvn -ntp versions:set -DnewVersion=${VERSION} -DgenerateBackupPoms=false
          git commit --allow-empty -am "chore: updating branch release-${VERSION}-${timestamp} with non-snapshot versions"
          git checkout develop
          mvn -ntp versions:set -DnewVersion=${NEW_VERSION}-SNAPSHOT -DgenerateBackupPoms=false
          git commit --allow-empty -am "chore: updating for ${NEW_VERSION}-SNAPSHOT develop [skip ci]"
          git merge --no-ff -m "Merge branch release-${VERSION}-${timestamp} into develop [skip ci]" -s ours release-${VERSION}-${timestamp}
          git remote set-branches origin "*"
          git fetch
          git checkout main
          git merge release-${VERSION}-${timestamp} --no-ff --strategy-option theirs --allow-unrelated-histories
          git branch -D release-${VERSION}-${timestamp}
          mvn -B clean verify
          git push origin main
          git checkout develop
          git push origin develop
